<a href="https://colab.research.google.com/github/thiago1590/Deep_Learning/blob/master/Estudo_redes_neurais_raw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Para um neuronio:**

In [20]:
inputs = [1.2,3.4,5.3,1.7]
weights = [3.1,5.4,2.3,3.9]
bias = 2
output = inputs[0]*weights[0] + inputs[1]*weights[1] +  inputs[2]*weights[2] +  inputs[3]*weights[3]  + bias
print(output)

42.9


**Para uma camada:**

In [15]:
inputs = [1.2,3.4,5.3,1.7]
weights1 = [3.1,5.4,2.3,3.9]
weights2 = [2.1,5.2,6.3,2.9]
weights3 = [5.1,2.2,2.3,5.9]
bias1 = 2
bias2 = 3
bias3 = 0.5

In [16]:
output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] +  inputs[2]*weights1[2] +  inputs[3]*weights1[3]  + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] +  inputs[2]*weights2[2] +  inputs[3]*weights2[3]  + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] +  inputs[2]*weights3[2] +  inputs[3]*weights3[3]  + bias3]
print(output)

[42.9, 61.52, 36.32]


**refatorando e usando numpy..**

In [18]:
inputs = [1.2,3.4,5.3,1.7]
weights = [[3.1,5.4,2.3,3.9],
           [2.1,5.2,6.3,2.9],
           [5.1,2.2,2.3,5.9]]
biases = [2,3,0.5]

output = np.dot(weights,inputs) + biases
print(output)

[42.9  61.52 36.32]


**Usando batches...**

In [26]:
inputs = [ [1.2,3.4,5.3,1.7],
           [2.3,4.1,3.2,4.7],
           [3.5,3.4,1.6,2.6] ]

weights = [ [3.1,5.4,2.3,3.9],
            [2.1,5.2,6.3,2.9],
            [5.1,2.2,2.3,5.9] ]

biases = [2,3,0.5]

output = np.dot(inputs,np.array(weights).T) + biases
print(output)


[[42.9  61.52 36.32]
 [56.96 62.94 56.34]
 [45.03 45.65 44.85]]
